import plugin from "tailwindcss/plugin";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        ds: {
          brand: {
            primary: "var(--color-brand-primary)",
            "primary-hover": "var(--color-brand-primary-hover)",
            "primary-active": "var(--color-brand-primary-active)",
            accent: "var(--color-brand-accent)",
            "accent-hover": "var(--color-brand-accent-hover)",
            "accent-active": "var(--color-brand-accent-active)",
            "accent-subtle": "var(--color-brand-accent-subtle)",
          },
          background: {
            page: "var(--color-bg-page)",
            surface: "var(--color-bg-surface)",
            "surface-muted": "var(--color-bg-surface-muted)",
            "surface-subtle": "var(--color-bg-surface-subtle)",
            inverse: "var(--color-bg-inverse)",
          },
          text: {
            default: "var(--color-text-default)",
            strong: "var(--color-text-strong)",
            muted: "var(--color-text-muted)",
            subtle: "var(--color-text-subtle)",
            inverse: "var(--color-text-inverse)",
            "on-accent": "var(--color-text-on-accent)",
          },
          border: {
            default: "var(--color-border-default)",
            muted: "var(--color-border-muted)",
            strong: "var(--color-border-strong)",
            focus: "var(--color-border-focus)",
          },
          success: {
            surface: "var(--color-success-surface)",
            border: "var(--color-success-border)",
            text: "var(--color-success-text)",
            solid: "var(--color-success-solid)",
            "solid-hover": "var(--color-success-solid-hover)",
          },
          warning: {
            surface: "var(--color-warning-surface)",
            border: "var(--color-warning-border)",
            text: "var(--color-warning-text)",
            solid: "var(--color-warning-solid)",
            "solid-hover": "var(--color-warning-solid-hover)",
          },
          danger: {
            surface: "var(--color-danger-surface)",
            border: "var(--color-danger-border)",
            text: "var(--color-danger-text)",
            solid: "var(--color-danger-solid)",
            "solid-hover": "var(--color-danger-solid-hover)",
          },
        },
      },
      spacing: {
        "ds-xs": "var(--space-xs)",
        "ds-sm": "var(--space-sm)",
        "ds-md": "var(--space-md)",
        "ds-lg": "var(--space-lg)",
        "ds-xl": "var(--space-xl)",
        "ds-2xl": "var(--space-2xl)",
        "ds-3xl": "var(--space-3xl)",
        "ds-4xl": "var(--space-4xl)",
        "ds-5xl": "var(--space-5xl)",
        "ds-6xl": "var(--space-6xl)",
        "xs": "4px",
        "sm": "8px",
        "md": "12px",
        "lg": "16px",
        "xl": "20px",
        "2xl": "24px",
        "3xl": "32px",
        "4xl": "48px",
        "5xl": "64px",
        "6xl": "72px",
      },
      borderRadius: {
        "ds-sm": "var(--radius-sm)",
        "ds-md": "var(--radius-md)",
        "ds-lg": "var(--radius-lg)",
        "ds-xl": "var(--radius-xl)",
        "ds-2xl": "var(--radius-2xl)",
        "ds-full": "var(--radius-full)",
        "sm": "4px",
        "md": "6px",
        "lg": "13px",
        "xl": "20px",
        "2xl": "24px",
      },
      fontSize: {
        "ds-display": ["var(--type-display-font-size)", { lineHeight: "var(--type-display-line-height)", letterSpacing: "var(--type-display-letter-spacing)", fontWeight: "var(--type-display-font-weight)" }],
        "ds-h1": ["var(--type-h1-font-size)", { lineHeight: "var(--type-h1-line-height)", letterSpacing: "var(--type-h1-letter-spacing)", fontWeight: "var(--type-h1-font-weight)" }],
        "ds-h2": ["var(--type-h2-font-size)", { lineHeight: "var(--type-h2-line-height)", letterSpacing: "var(--type-h2-letter-spacing)", fontWeight: "var(--type-h2-font-weight)" }],
        "ds-h3": ["var(--type-h3-font-size)", { lineHeight: "var(--type-h3-line-height)", letterSpacing: "var(--type-h3-letter-spacing)", fontWeight: "var(--type-h3-font-weight)" }],
        "ds-h4": ["var(--type-h4-font-size)", { lineHeight: "var(--type-h4-line-height)", letterSpacing: "var(--type-h4-letter-spacing)", fontWeight: "var(--type-h4-font-weight)" }],
        "ds-body-lg": ["var(--type-body-lg-font-size)", { lineHeight: "var(--type-body-lg-line-height)", letterSpacing: "var(--type-body-lg-letter-spacing)", fontWeight: "var(--type-body-lg-font-weight)" }],
        "ds-body": ["var(--type-body-font-size)", { lineHeight: "var(--type-body-line-height)", letterSpacing: "var(--type-body-letter-spacing)", fontWeight: "var(--type-body-font-weight)" }],
        "ds-body-sm": ["var(--type-body-sm-font-size)", { lineHeight: "var(--type-body-sm-line-height)", letterSpacing: "var(--type-body-sm-letter-spacing)", fontWeight: "var(--type-body-sm-font-weight)" }],
        "ds-caption": ["var(--type-caption-font-size)", { lineHeight: "var(--type-caption-line-height)", letterSpacing: "var(--type-caption-letter-spacing)", fontWeight: "var(--type-caption-font-weight)" }],
        "ds-label": ["var(--type-label-font-size)", { lineHeight: "var(--type-label-line-height)", letterSpacing: "var(--type-label-letter-spacing)", fontWeight: "var(--type-label-font-weight)" }],
        "ds-button": ["var(--type-button-font-size)", { lineHeight: "var(--type-button-line-height)", letterSpacing: "var(--type-button-letter-spacing)", fontWeight: "var(--type-button-font-weight)" }],
        "xs": ["12px", "14px"],
        "sm": ["14px", "16px"],
        "base": ["16px", "1.333"],
        "lg": ["18px", "20px"],
        "xl": ["21px", "24px"],
        "2xl": ["24px", "28px"],
        "3xl": ["36px", "42px"],
      },
      boxShadow: {
        "ds-sm": "var(--shadow-sm)",
        "ds-md": "var(--shadow-md)",
        "ds-lg": "var(--shadow-lg)",
        "sm": "var(--shadow-sm)",
        "md": "var(--shadow-md)",
        "lg": "var(--shadow-lg)",
      },
    },
  },
  plugins: [
    plugin(function ({ addUtilities }) {
      addUtilities({
        ".ds-type-display": {
          fontFamily: "var(--font-family-sans)",
          fontSize: "var(--type-display-font-size)",
          lineHeight: "var(--type-display-line-height)",
          letterSpacing: "var(--type-display-letter-spacing)",
          fontWeight: "var(--type-display-font-weight)",
        },
        ".ds-type-h1": {
          fontFamily: "var(--font-family-sans)",
          fontSize: "var(--type-h1-font-size)",
          lineHeight: "var(--type-h1-line-height)",
          letterSpacing: "var(--type-h1-letter-spacing)",
          fontWeight: "var(--type-h1-font-weight)",
        },
        ".ds-type-h2": {
          fontFamily: "var(--font-family-sans)",
          fontSize: "var(--type-h2-font-size)",
          lineHeight: "var(--type-h2-line-height)",
          letterSpacing: "var(--type-h2-letter-spacing)",
          fontWeight: "var(--type-h2-font-weight)",
        },
        ".ds-type-h3": {
          fontFamily: "var(--font-family-sans)",
          fontSize: "var(--type-h3-font-size)",
          lineHeight: "var(--type-h3-line-height)",
          letterSpacing: "var(--type-h3-letter-spacing)",
          fontWeight: "var(--type-h3-font-weight)",
        },
        ".ds-type-h4": {
          fontFamily: "var(--font-family-sans)",
          fontSize: "var(--type-h4-font-size)",
          lineHeight: "var(--type-h4-line-height)",
          letterSpacing: "var(--type-h4-letter-spacing)",
          fontWeight: "var(--type-h4-font-weight)",
        },
        ".ds-type-body-lg": {
          fontFamily: "var(--font-family-sans)",
          fontSize: "var(--type-body-lg-font-size)",
          lineHeight: "var(--type-body-lg-line-height)",
          letterSpacing: "var(--type-body-lg-letter-spacing)",
          fontWeight: "var(--type-body-lg-font-weight)",
        },
        ".ds-type-body": {
          fontFamily: "var(--font-family-sans)",
          fontSize: "var(--type-body-font-size)",
          lineHeight: "var(--type-body-line-height)",
          letterSpacing: "var(--type-body-letter-spacing)",
          fontWeight: "var(--type-body-font-weight)",
        },
        ".ds-type-body-sm": {
          fontFamily: "var(--font-family-sans)",
          fontSize: "var(--type-body-sm-font-size)",
          lineHeight: "var(--type-body-sm-line-height)",
          letterSpacing: "var(--type-body-sm-letter-spacing)",
          fontWeight: "var(--type-body-sm-font-weight)",
        },
        ".ds-type-caption": {
          fontFamily: "var(--font-family-sans)",
          fontSize: "var(--type-caption-font-size)",
          lineHeight: "var(--type-caption-line-height)",
          letterSpacing: "var(--type-caption-letter-spacing)",
          fontWeight: "var(--type-caption-font-weight)",
        },
        ".ds-type-label": {
          fontFamily: "var(--font-family-sans)",
          fontSize: "var(--type-label-font-size)",
          lineHeight: "var(--type-label-line-height)",
          letterSpacing: "var(--type-label-letter-spacing)",
          fontWeight: "var(--type-label-font-weight)",
        },
        ".ds-type-button": {
          fontFamily: "var(--font-family-sans)",
          fontSize: "var(--type-button-font-size)",
          lineHeight: "var(--type-button-line-height)",
          letterSpacing: "var(--type-button-letter-spacing)",
          fontWeight: "var(--type-button-font-weight)",
        },
      });
    }),
  ],
  darkMode: "class",
  safelist: [
    "bg-ds-background-surface",
    "bg-ds-warning-solid",
    "bg-ds-success-solid",
    "bg-ds-danger-solid",
    "bg-black",
    "text-white",
    "text-ds-text-default",
    "text-ds-text-on-accent",
    "text-ds-text-inverse",
    "flex-1",
  ]
}
